### PR TITLE
Add automatic pull requests version updates

### PR DESCRIPTION
**Pull request by Mailaender**
Note: this requires `GH_TOKEN` from a committer set in the repository secrets for it to work.

### CODE REVIEW

**Comment by jfaltermeier** [comment]
Thanks, this looks good to me. I believe GH_TOKEN should be available by default based on the permissions.

I’ll work on narrowing down the required permissions in follow-up PRs once we have a new release to properly test this.

**Comment by jfaltermeier** [comment]
We have some formatting changes, but these should be gone after the first run I guess: https://github.com/eclipse-theia/theia-ide-snap/pull/10/files

**Comment by jfaltermeier** [comment]
One side effect is that, since the GitHub Actions user is not a committer, a committer will need to force-push the changes to trigger the verification builds. However, this is similar to the behavior we have for automated translations in the Theia repository, so I think this is fine.

**Comment by jfaltermeier** [comment]
After formatting changes are merged it works as expected: https://github.com/eclipse-theia/theia-ide-snap/actions/runs/12410207420/job/34645346568

**Comment by Mailaender** [comment]
You could create a bot account that has the ECA signed and use its credentials instead.

**Pull request merged**
